id = "esmerald-theme"
submodule = "extensions/esmerald"
version = "0.1.0"
name = "Esmerald"
schema_version = 1
authors = ["Esteban H. Acevedo A."]
description = "💎 It's a beautiful theme for Zed Editor"
repository = "https://github.com/esthorace/esmerald-zed.git"
